apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust-master
        image: <Dockerfile.m image here>
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8089
